//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiChzk1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryServiceStatus
    {
        public int deliveryServiceStatusId { get; set; }
        public int deliveryServiceId { get; set; }
        public string status { get; set; }
        public byte[] dateStatus { get; set; }
        public string reason { get; set; }
    
        public virtual DeliveryService DeliveryService { get; set; }
        public virtual DeliveryStatus DeliveryStatus { get; set; }
    }
}
