//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiChzk1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListItemSold
    {
        public int itemSoldId { get; set; }
        public int deliveryTrackCode { get; set; }
        public string product { get; set; }
        public string currency { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public string size { get; set; }
    
        public virtual Currency Currency1 { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual DeliverySize DeliverySize { get; set; }
    }
}
