//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiChzk1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chzkEntities : DbContext
    {
        public chzkEntities()
            : base("name=chzkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressClient> AddressClient { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<Delivery> Delivery { get; set; }
        public virtual DbSet<DeliveryService> DeliveryService { get; set; }
        public virtual DbSet<DeliveryServiceStatus> DeliveryServiceStatus { get; set; }
        public virtual DbSet<DeliverySize> DeliverySize { get; set; }
        public virtual DbSet<DeliveryStatus> DeliveryStatus { get; set; }
        public virtual DbSet<DocumentType> DocumentType { get; set; }
        public virtual DbSet<ListItemSold> ListItemSold { get; set; }
        public virtual DbSet<Mode> Mode { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethod { get; set; }
        public virtual DbSet<ProofPayment> ProofPayment { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<TimeZone> TimeZone { get; set; }
    }
}
